export const PATHS = {
  login: "/login",
  signup: "/sign-up",
  dashboard: "/dashboard",
  vehicleManagement: "/dashboard/vehicle-management",
  webPage: "/dashboard/webpage",
  garageSetting: "/dashboard/garage-setting",
  templatePrint: "/dashboard/template",
  singleVehicleManagement: "/dashboard/vehicle-management/:id",
  singleVehicleDetails: "/dashboard/vehicle-details/:id",
  financialManagement: "/dashboard/financial-management",
  contractManagement: "/dashboard/contract-management",
  contractDetails: "/dashboard/contract-management/:id",
  contractTemplatesDetails: "/dashboard/contract-templates/:id",
  customerManagement: "/dashboard/customer-management",
  customerDetails: "/dashboard/customer-details/:id",
  inventoryManagement: "/dashboard/inventory-management",
  inquiryManagement: "/dashboard/inquiry-management",
  inquiryDetail: "/dashboard/inquiry-management/:id",
  inquiryMailbox: "/dashboard/inquiry-management/:id/mailbox/:id",
  informationClientDetail:
    "/dashboard/inquiry-management/:id/mailbox/:id/client-information",
  chatOpen:
    "/dashboard/inquiry-management/:id/mailbox/:id/client-information/chat",

  quotationManagement: "/dashboard/quotation-management",
  quotationDetail: "/dashboard/quotation-detail/:id",
  calendar: "/dashboard/calendar",
  carDetails: "/car-details/:id",

  //  user settings
  myProfile: "/dashboard/settings/my-profile",
  myUsers: "/dashboard/settings/my-users",
  userDetail: "/dashboard/settings/my-users/:id",
  workPlan: "/dashboard/settings/work-plan",
  holidayPlan: "/dashboard/settings/holiday-plan",
  accounting: "/dashboard/accounting",
  interfaces: "/dashboard/interface",
  tariffAndPayments: "/dashboard/tarrif-and-payments",
  // home page
  PublicWebPage: "/webpage/:webpageId",
  vehiclesList: "/vehicle-list/:webpageId",
  singleCatalogDetail: "/vehicle-detail/:webpageId",
  vehicleRequest: "/request/:webpageId",
  singleCustomerDetails: "/dashboard/customer-management/:id",
  birthdayRoute: "/dashboard/birthday-list",
  cashBookRoute: "/dashboard/cashbook",
  reportRoute: "/dashboard/reports",
  vehicleCheckRoute: "/dashboard/vehicle-check",
  vehicleCheckDetailRoute: "/dashboard/vehicle-detail/:id",
  vehicleAssementDetailRoute: "/dashboard/vehicle-assessment/detail/:id",
  email: "/dashboard/email",
  trash: "/dashboard/trash",
  //  Invoice Page
  ProfitAndInvoices: "/dashboard/profit-&-invoices",
  invoiceDetail: "/dashboard/profit-&-invoices/:id",
  newInvoice: "/dashboard/profit-&-invoices/new-invoice",
};
export default PATHS;
