import * as Yup from "yup";

const currentYear = new Date().getFullYear();
const manufactureYearOptions = Array.from(
  { length: currentYear - 1890 + 1 },
  (_, index) => {
    const year = currentYear - index;
    return { value: year.toString(), label: year.toString() };
  }
);

const bodyTypes = [
  { value: "", label: "" },
  { value: "sedan", label: "Sedan" },
  { value: "coupe", label: "Coupe" },
  { value: "hatchback", label: "Hatchback" },
  { value: "convertible", label: "Convertible" },
  { value: "suv", label: "SUV" },
  { value: "crossover", label: "Crossover" },
  { value: "wagon", label: "Wagon (Station Wagon)" },
  { value: "minivan", label: "Minivan" },
  { value: "pickup", label: "Pickup Truck" },
  { value: "roadster", label: "Roadster" },
  { value: "truck", label: "Full-size Truck" },
  { value: "sports_car", label: "Sports Car" },
  { value: "luxury_car", label: "Luxury Car" },
  { value: "cabriolet", label: "Cabriolet" },
  { value: "suv_coupe", label: "SUV Coupe" },
  { value: "van", label: "Van" },
];

const vehicleValidation = Yup.object({
  image1: Yup.mixed().required("Image 1 is required"),
  image2: Yup.mixed().required("Image 2 is required"),
  image3: Yup.mixed().required("Image 3 is required"),
  image4: Yup.mixed().required("Image 4 is required"),
  stockNo: Yup.string().required("Stock number is required"),
  year: Yup.number()
    .required("Year is required")
    .min(1886, "Year must be 1886 or later")
    .max(new Date().getFullYear(), "Year can't be in the future"),
  price: Yup.number()
    .required("Price is required")
    .min(0, "Price must be non-negative"),
  mileage: Yup.number()
    .required("Mileage is required")
    .min(0, "Mileage must be non-negative"),
  location: Yup.string().required("Location is required"),
  status: Yup.string()
    .oneOf(["available", "sold", "reserved"], "Invalid status")
    .required("Status is required"),
  brand: Yup.string().required("Brand is required"),
  model: Yup.string().required("Model is required"),
  type: Yup.string().required("Body type is required"),
  vehicleId: Yup.string().required("Vehicle ID is required"), // Add validation for vehicleId
});

const editVehicleValidation = Yup.object({
  image1: Yup.mixed().notRequired(),
  image2: Yup.mixed().notRequired(),
  image3: Yup.mixed().notRequired(),
  image4: Yup.mixed().notRequired(),
  stockNo: Yup.string().required("Stock number is required"),
  brand: Yup.string().required("Brand is required"),
  model: Yup.string().required("Model is required"),
  type: Yup.string().required("Body type is required"),
  year: Yup.number()
    .required("Year is required")
    .min(1886, "Year must be 1886 or later")
    .max(new Date().getFullYear(), "Year can't be in the future"),
  price: Yup.number()
    .required("Price is required")
    .min(0, "Price must be non-negative"),
  mileage: Yup.number()
    .required("Mileage is required")
    .min(0, "Mileage must be non-negative"),
  location: Yup.string().required("Location is required"),
  vehicleId: Yup.string().required("Vehicle ID is required"),
});
const editInitialValues = {
  image1: null,
  image2: null,
  image3: null,
  image4: null,
  stockNo: "",
  brand: "",
  model: "",
  type: "",
  year: "",
  price: "",
  mileage: "",
  location: "",
  status: "",
  vehicleId: "",
};

const addVehicleFirst = [
  {
    name: "chooseVehicle",
    label: "Choose Vehicle",
  
    type: "select",
    
    options: [
      // { value: "", label: "select an option" },
      { value: "Typengenemigung", label: "Type approval" },
      { value: "Stammnummer", label: "Reference number" },
      { value: "Make and Model", label: "Make and Model" },
    ],
  },
  {
    name: "fahrzeugart",
    label: "Vehicle Type",
    placeholder: "Passenger Car",
    type: "text",
    required: true,
    options: [
      { value: "", label: "Passenger Car" },
      { value: "active", label: "Active" },
      { value: "inactive", label: "Inactive" },
      { value: "follow-up", label: "Follow-Up" },
    ],
  },

  {
    name: "TG",
    label: "Type Approval",
    type: "text",
    required: true,
    placeholder: "Number 24 Vehicle Registration Document",
  },
  {
    name: "manufacture_month",
    label: "Month of Manufacture",
    type: "select",
    required: true,
    placeholder: "June",
    options: [
      { value: "", label: "Choose month" },
      { value: "1", label: "January" },
      { value: "2", label: "Fabruary" },
      { value: "3", label: "March" },
      { value: "4", label: "April" },
      { value: "5", label: "May" },
      { value: "6", label: "June" },
      { value: "7", label: "July" },
      { value: "8", label: "August" },
      { value: "9", label: "September" },
      { value: "10", label: "October" },
      { value: "11", label: "November" },
      { value: "12", label: "December" },
    ],
  },
  {
    name: "manufactureYear",
    label: "Year of Manufacture",
    type: "select",
    required: true,
    placeholder: "2025",
    options: [{ value: "", label: "Choose year" }, ...manufactureYearOptions],
  },
];
const addVehicleThird = [
  {
    name: "make",
    label: "Make",
    placeholder: "Enter Make",
    required: true,
    type: "select",
  },
  {
    name: "model",
    label: "Model",
    placeholder: "Enter Model",
    required: true,
    type: "select",
  },

  {
    name: "version",
    label: "Version",
    placeholder: "Enter Version",
    required: true,
    type: "text",
  },
  {
    name: "location",
    label: "Location",
    placeholder: "Enter Version",
    required: true,
    type: "text",
  },
  {
    name: "trunkNumber",
    label: "Trunk Number",
    placeholder: "Enter Version",
    required: true,
    type: "text",
  },
  {
    name: "bodyType",
    label: "Body Type",
    placeholder: "Cabrio",
    required: true,
    type: "select",
    options : [
      { value: "", label: "Select body type" },
      { value: "sedan", label: "Sedan" },
      { value: "hatchback", label: "Hatchback" },
      { value: "suv", label: "SUV" },
      { value: "crossover", label: "Crossover" },
      { value: "coupe", label: "Coupe" },
      { value: "convertible", label: "Convertible" },
      { value: "wagon", label: "Wagon" },
      { value: "pickup", label: "Pickup Truck" },
      { value: "minivan", label: "Minivan" },
      { value: "van", label: "Van" },
      { value: "roadster", label: "Roadster" },
      { value: "sports_car", label: "Sports Car" },
      { value: "luxury_sedan", label: "Luxury Sedan" },
      { value: "offroad", label: "Off-Road Vehicle" },
      { value: "microcar", label: "Microcar" },
      { value: "limousine", label: "Limousine" },
      { value: "jeep", label: "Jeep" },
      { value: "targa", label: "Targa" },
      { value: "fastback", label: "Fastback" },
      { value: "shooting_brake", label: "Shooting Brake" },
      { value: "muscle_car", label: "Muscle Car" },
      { value: "electric_sedan", label: "Electric Sedan" },
      { value: "electric_suv", label: "Electric SUV" },
      { value: "kei_car", label: "Kei Car" },
      { value: "campervan", label: "Campervan" },
      { value: "bus", label: "Bus" },
      { value: "station_wagon", label: "Station Wagon" },
      { value: "ute", label: "Ute (Utility Vehicle)" },
      { value: "dune_buggy", label: "Dune Buggy" },
      { value: "hearse", label: "Hearse" },
      { value: "fire_truck", label: "Fire Truck" },
      { value: "police_car", label: "Police Car" },
      { value: "armored_vehicle", label: "Armored Vehicle" }
    ]
  },
  {
    name: "vehicleType",
    label: "Type",
    required: true,
    type: "select",
    options: [
      { value: "", label: "Select vehicle type" },
      { value: "automatic", label: "Automatic" },
      { value: "manual", label: "Manual" },
      { value: "semi_automatic", label: "Semi-Automatic" },
      { value: "cvt", label: "Continuously Variable Transmission (CVT)" },
      { value: "dual_clutch", label: "Dual-Clutch Transmission (DCT)" },
      { value: "tiptronic", label: "Tiptronic" },
      { value: "direct_shift", label: "Direct Shift Gearbox (DSG)" },
      { value: "torque_converter", label: "Torque Converter Automatic" },
      { value: "sequential_manual", label: "Sequential Manual Transmission (SMT)" },
      { value: "single_speed", label: "Single-Speed Transmission (EVs)" },
    ],
  },
  {
    name: "fuel",
    label: "Fuel",
    required: true,
    placeholder: "Petrol",
    type: "select",
    options : [
      { value: "", label: "Select fuel type" },
      { value: "petrol", label: "Petrol (Gasoline)" },
      { value: "diesel", label: "Diesel" },
      { value: "electric", label: "Electric" },
      { value: "hybrid_petrol", label: "Hybrid (Petrol-Electric)" },
      { value: "hybrid_diesel", label: "Hybrid (Diesel-Electric)" },
      { value: "phev", label: "Plug-in Hybrid (PHEV)" },
      { value: "hydrogen_fuel_cell", label: "Hydrogen Fuel Cell" },
      { value: "cng", label: "CNG (Compressed Natural Gas)" },
      { value: "lpg", label: "LPG (Liquefied Petroleum Gas)" },
      { value: "ethanol", label: "Ethanol (Flex Fuel / E85)" },
      { value: "biodiesel", label: "Biodiesel" },
      { value: "methanol", label: "Methanol" },
      { value: "propane", label: "Propane" },
      { value: "synthetic_fuel", label: "Synthetic Fuel (eFuel)" },
      { value: "solar", label: "Solar-Powered" },
      { value: "hydrogen_ic", label: "Hydrogen Internal Combustion" },
      { value: "biogas", label: "Biogas" }
    ]
    
  },
  {
    name: "drive",
    label: "Drive",
    required: true,
    type: "select",
    placeholder: "rear-wheel drive",
    options: [
      { value: "", label: "select option" },
      { value: "fwd", label: "Front-Wheel Drive (FWD)" },
      { value: "rwd", label: "Rear-Wheel Drive (RWD)" },
      { value: "awd", label: "All-Wheel Drive (AWD)" },
      { value: "4wd", label: "Four-Wheel Drive (4WD)" },
      { value: "part_time_4wd", label: "Part-Time 4WD" },
      { value: "full_time_4wd", label: "Full-Time 4WD" },
      { value: "on_demand_awd", label: "On-Demand AWD" },
      { value: "electric_awd", label: "Electric AWD" }
    ],
  },
  {
    name: "seats",
    label: "Seats",
    required: true,
    type: "select",
    placeholder: "4",
    options: [
      { value: "", label: "Select Seats" },
      { value: "2", label: "2-Seater (Sports Car, Coupe)" },
      { value: "4", label: "4-Seater (Compact Car, Coupe)" },
      { value: "5", label: "5-Seater (Sedan, Hatchback, SUV)" },
      { value: "6", label: "6-Seater (SUV, MPV with Captain Seats)" },
      { value: "7", label: "7-Seater (Large SUV, Minivan)" },
      { value: "8", label: "8-Seater (Full-Size SUV, Van)" },
      { value: "9", label: "9-Seater (Passenger Van, Shuttle)" },
      { value: "10", label: "10+ Seater (Minibus, Large Van)" },
    ]
  },
  {
    name: "doors",
    label: "Doors",
    required: true,
    type: "select",
    options: [
      { value: "", label: "Select doors" },
      { value: "2", label: "2-Door (Coupe, Convertible, Sports Car)" },
      { value: "3", label: "3-Door (Hatchback with Rear Access)" },
      { value: "4", label: "4-Door (Sedan, Compact Car, SUV)" },
      { value: "5", label: "5-Door (Hatchback, SUV, Crossover)" },
      { value: "6", label: "6-Door (Extended SUV, Special Vehicles)" },
    
    ]
  },
  {
    name: "psKw",
    label: "PS/KW ",
    required: true,
    placeholder: "218 ps",
    type: "text",
  },
  {
    name: "capacity_cm3",
    label: "capacity (cm3)  ",
    required: true,
    placeholder: "2996",
    type: "number",
  },
  {
    name: "cylinder",
    label: "cylinder",
    required: true,
    type: "number",
    placeholder: "6",
  },
  {
    name: "noOfGears",
    label: "Number Of Gears",
    required: true,
    type: "number",
    placeholder: "6",
  },
  {
    name: "wheelbase_mm",
    label: "wheelbase (Mm) ",
    required: true,
    placeholder: "2760",
    type: "number",
  },
  {
    name: "trailerLoad_kg",
    label: "Trailer Load (kg)  ",
    required: true,
    type: "number",
    placeholder: "150",
  },
  {
    name: "typeApproval",
    label: "Type Approval",
    required: true,
    placeholder: "1600",
    type: "text",
  },
  {
    name: "curbWeight_kg",
    label: "Curb Weight (kg) ",
    required: true,
    placeholder: "1730",
    type: "number",
  },
  {
    name: "payload_kg",
    label: "Payload",
    required: true,
    type: "number",
    placeholder: "335",
  },
  {
    name: "firstRegistration",
    label: "First Registration ",
    required: true,
    type: "date",
    placeholder: "5.2012",
  },
  {
    name: "co2Emission_G_km",
    label: "CO2-Emission (g/km) ",
    required: true,
    placeholder: "176",
    type: "number",
  },
  {
    name: "energyLabel",
    label: "Energy label ",
    required: true,
    type: "text",
    placeholder: "F",
  },
  {
    name: "emissionStandard",
    label: "Emission standard",
    required: true,
    type: "select",
    options: [
      { value: "", label: "Select Options" },
      { value: "euro1", label: "Euro 1" },
      { value: "euro2", label: "Euro 2" },
      { value: "euro3", label: "Euro 3" },
      { value: "euro4", label: "Euro 4" },
      { value: "euro5", label: "Euro 5" },
    ],
  },
  {
    name: "consumption_L_100km",
    label: "consumption (l/100 km)",
    required: true,
    type: "number",
    placeholder: "10.2 5.9 7.5",
  },
  {
    name: "standardEquipment",
    label: "standard Equipment",
    required: true,
    type: "text",
    placeholder: "10.2 5.9 7.5",
  },
];
const makeAndModelSecondInputs = [
  {
    name: "Make",
    label: "Make",
    placeholder: "Select Make",
    required: true,
    type: "select",
    options: [{ value: "-", label: "Select Make" }],
  },
  {
    name: "Model",
    label: "Model",
    placeholder: "Select Model",
    required: true,
    type: "select",
    options: [{ value: "-", label: "Select Model" }],
  },
  {
    name: "version",
    label: "Version",
    required: true,
    placeholder: "Enter version",
    type: "text",
  },
  {
    name: "bodyType",
    label: "Body Type",
    required: true,
    placeholder: "Select Type",
    type: "select",
  },
  {
    name: "vehicleColor",
    label: "Vehicle Color",
    required: true,
    type: "select",
    placeholder: " Vehicle Color",
    options: [{ value: "-", label: "Select Vehicle Color" }],
  },
  {
    name: "interiorColor ",
    label: "Interior Color ",
    required: true,
    type: "select",
    placeholder: "Select Interior Color ",
    options: [{ value: "-", label: "Select Interior Color " }],
  },
  {
    name: "transmission ",
    label: "Transmission ",
    required: true,
    type: "select",
    placeholder: "Select Transmission ",
    options: [{ value: "-", label: "Select Transmission " }],
  },
  {
    name: "Type ",
    label: "Type ",
    required: true,
    type: "select",
    placeholder: "Select Type ",
    options: [{ value: "-", label: "Select Type " }],
  },
  {
    name: "Drive",
    label: "Drive ",
    required: true,
    type: "select",
    placeholdDrer: "Select Drive ",
    options: [{ value: "-", label: "Select Drive " }],
  },
  {
    name: "fule",
    label: "Fule ",
    required: true,
    type: "select",
    placeholdDrer: "Select Fule ",
    options: [{ value: "-", label: "Select Fule " }],
  },
];
const makeAndModelSecondConditionInputs = [
  {
    name: "vehicleCondition ",
    label: "Vehicle Condition ",
    placeholder: "Select Vehicle Condition ",
    required: true,
    type: "select",
    options: [{ value: "-", label: "Select Select Vehicle Condition " }],
  },
  {
    name: "firstRegistration  ",
    label: "firstRegistration  ",
    placeholder: "Select Vehicle Condition ",
    required: true,
    type: "date",
  },
  {
    name: "kilometer",
    label: "kilometer",
    placeholder: " kilometer",
    required: true,
    type: "number",
  },
  {
    name: "lastMOT",
    label: "last MOT",
    placeholder: "Enter last MOT",
    type: "date",
  },
  {
    name: "AbMFK",
    label: "Ab MFK",
    placeholder: "Enter last Ab MFK",
    type: "checkbox",
  },

  {
    name: "warranty",
    label: "Warranty",
    required: true,
    placeholder: "Select warranty",
    type: "select",
    options: [{ value: "-", label: "warranty" }],
  },
];
const vehicleFeatures = [
  {
    name: "vehicleColor",
    label: "vehicle Color ",
    required: true,
    type: "select",
    placeholder: "Choose Color",
    options: [
      { value: "", label: "Choose Color" },
      { value: "black", label: "Black" },
      { value: "white", label: "White" },
      { value: "gray", label: "Gray" },
      { value: "silver", label: "Silver" },
      { value: "red", label: "Red" },
      { value: "blue", label: "Blue" },
      { value: "green", label: "Green" },
      { value: "yellow", label: "Yellow" },
      { value: "orange", label: "Orange" },
      { value: "brown", label: "Brown" },
      { value: "beige", label: "Beige" },
      { value: "purple", label: "Purple" },
      { value: "pink", label: "Pink" },
      { value: "gold", label: "Gold" },
      { value: "bronze", label: "Bronze" },
      { value: "turquoise", label: "Turquoise" },
      { value: "violet", label: "Violet" },
      { value: "multicolor", label: "Multicolor" },
      { value: "champagne", label: "Champagne" },
      { value: "burgundy", label: "Burgundy" },
      { value: "copper", label: "Copper" },
      { value: "graphite", label: "Graphite" },
      { value: "charcoal", label: "Charcoal" },
      { value: "navy", label: "Navy Blue" },
      { value: "midnightblue", label: "Midnight Blue" },
      { value: "skyblue", label: "Sky Blue" },
      { value: "lime", label: "Lime Green" },
      { value: "olive", label: "Olive Green" },
      { value: "mint", label: "Mint Green" },
      { value: "teal", label: "Teal" },
      { value: "rose", label: "Rose" },
      { value: "lavender", label: "Lavender" },
      { value: "matteblack", label: "Matte Black" },
      { value: "mattegray", label: "Matte Gray" },
      { value: "matteblue", label: "Matte Blue" },
      { value: "mattered", label: "Matte Red" },
      { value: "pearlwhite", label: "Pearl White" },
      { value: "chameleon", label: "Chameleon" },
      { value: "carbonfiber", label: "Carbon Fiber" },
      { value: "custom", label: "Custom Color" },
    ],
  },
  {
    name: "interiorColor",
    label: "Interior Color ",
    required: false,
    type: "select",
    options: [
      { value: "", label: "Choose Color" },
      { value: "black", label: "Black" },
      { value: "white", label: "White" },
      { value: "gray", label: "Gray" },
      { value: "silver", label: "Silver" },
      { value: "red", label: "Red" },
      { value: "blue", label: "Blue" },
      { value: "green", label: "Green" },
      { value: "yellow", label: "Yellow" },
      { value: "orange", label: "Orange" },
      { value: "brown", label: "Brown" },
      { value: "beige", label: "Beige" },
      { value: "purple", label: "Purple" },
      { value: "pink", label: "Pink" },
      { value: "gold", label: "Gold" },
      { value: "bronze", label: "Bronze" },
      { value: "turquoise", label: "Turquoise" },
      { value: "violet", label: "Violet" },
      { value: "multicolor", label: "Multicolor" },
      { value: "champagne", label: "Champagne" },
      { value: "burgundy", label: "Burgundy" },
      { value: "copper", label: "Copper" },
      { value: "graphite", label: "Graphite" },
      { value: "charcoal", label: "Charcoal" },
      { value: "navy", label: "Navy Blue" },
      { value: "midnightblue", label: "Midnight Blue" },
      { value: "skyblue", label: "Sky Blue" },
      { value: "lime", label: "Lime Green" },
      { value: "olive", label: "Olive Green" },
      { value: "mint", label: "Mint Green" },
      { value: "teal", label: "Teal" },
      { value: "rose", label: "Rose" },
      { value: "lavender", label: "Lavender" },
      { value: "matteblack", label: "Matte Black" },
      { value: "mattegray", label: "Matte Gray" },
      { value: "matteblue", label: "Matte Blue" },
      { value: "mattered", label: "Matte Red" },
      { value: "pearlwhite", label: "Pearl White" },
      { value: "chameleon", label: "Chameleon" },
      { value: "carbonfiber", label: "Carbon Fiber" },
      { value: "custom", label: "Custom Color" },
    ],
  },
];
const vehicleConditionInputs = [
  {
    name: "vehicleCondition",
    label: "Vehicle Condition",
    required: true,
    type: "select",
    placeholder: "choose condition",
    options: [
      { value: "", label: "Choose Condition" },
      { value: "newVehicle", label: "New Vehicle" },
      { value: "occasion", label: "Occasion" },
      { value: "vintageCars", label: "Vintage Cars" },
      { value: "demonstrationModal", label: "Demonstration model" },
    ],
  },
  {
    name: "kilometer",
    label: "Kilometer",
    required: true,
    type: "number",
  },
  {
    name: "lastMOT",
    label: "last MOT",
    // required: true,
    type: "date",
    placeholder: "TT.MM.YYYY",
  },
  {
    name: "lastMFK",
    label: "Last MFK",
    // required: true,
    type: "date",
    placeholder: "TT.MM.YYYY",
  },
  {
    name: "abMFK",
    label: "Ab MFK",
    // required: true,
    type: "checkbox",
  },
  {
    name: "warranty",
    label: "Warranty",
    required: true,
    type: "select",

    placeholder: "choose warranty",
    options: [
      { value: "", label: "Choose Warranty" },
      { value: "1Year", label: "1 Year" },
      { value: "2Years", label: "2 Years" },
      { value: "3Years", label: "3 Years" },
      { value: "4years", label: "4 Years" },
    ],
  },
];

const vehiclePriceInputs = [
  {
    name: "sellingPrice_CHF",
    label: "Selling price - CHF  ",
    required: true,
    type: "number",
    // options: [{ value: "-", label: "-" }],
  },
  {
    name: "newPrice_CHF",
    label: "New Price - CHF",
    required: true,
    type: "number",
    // options: [{ value: "-", label: "-" }],
  },
];
const optionalEquipmentInput = [
  {
    name: "storagePackage",
    label: "Storage package",
    type: "checkbox",
  },
  {
    name: "adaptiveCruiseControl",
    label: "Adaptive cruise control",
    type: "checkbox",
  },
  {
    name: "adaptiveCorneringLights",
    label: "Adaptive cornering lights",
    type: "checkbox",
  },
  {
    name: "alarmSystem",
    label: "Alarm system with interior monitoring and tilt sensor",
    type: "checkbox",
  },
  {
    name: "towbar",
    label: "Towbar with detachable attachment",
    type: "checkbox",
  },
  {
    name: "apps",
    label: "Apps",
    type: "checkbox",
  },
  {
    name: "assistParkRear",
    label: "Assist: Park Distance Control (rear)",
    type: "checkbox",
  },
  {
    name: "assistParkFrontRear",
    label: "Assist: Park Distance Control (front and rear)",
    type: "checkbox",
  },
  {
    name: "exteriorMirrorPackage",
    label: "Exterior mirror package",
    type: "checkbox",
  },
  {
    name: "fineWoodTrim",
    label: "BMW Individual fine wood trim",
    type: "checkbox",
  },
  {
    name: "extendedIndividual",
    label: "BMW Individual extended",
    type: "checkbox",
  },
  {
    name: "woodInlays",
    label: "BMW Individual wood inlays for",
    type: "checkbox",
  },
  {
    name: "compositionIndividual",
    label: "BMW Individual composition",
    type: "checkbox",
  },
];
const optionalEquipmentTwoInput = [
  {
    name: "height_mm",
    label: "Height (Mm)",
    type: "number",
  },
  {
    name: "width_mm",
    label: "Width (Mm)",
    type: "number",
  },
  {
    name: "length_mm",
    label: "length (Mm)",
    type: "number",
  },
  {
    name: "VIN",
    label: "Vehicle Identification Number (VIN)",
    type: "text",
  },
  {
    name: "serialNumber",
    label: "Serial Number",
    type: "text",
  },
  {
    name: "referenceNumber",
    label: "Reference Number",
    type: "text",
  },
];
const technicaldataInputs = [
  {
    name: "Seats",
    label: "Seats ",
    type: "number",
    required: true,
    placeholder: "4",
  },
  {
    name: "Doors",
    label: "Doors ",
    type: "number",
    required: true,
    placeholder: "4",
  },
  {
    name: "PS ",
    label: "PS ",
    type: "number",
    required: true,
    placeholder: "260",
  },
  {
    name: "Kw ",
    label: "Kw ",
    type: "number",
    required: true,
    placeholder: "260",
  },
  {
    name: "Wheelbase (mm)  ",
    label: "Wheelbase (mm)  ",
    type: "number",
    required: true,
    placeholder: "260",
  },
  {
    name: "Trailer Load (kg)  ",
    label: "Trailer Load (kg)  ",
    type: "number",
    required: true,
    placeholder: "260",
  },
  {
    name: "Payload (kg)",
    label: "Payload (kg)  ",
    type: "number",
    required: true,
    placeholder: "260",
  },
  {
    name: "height",
    label: "Height (mm)",
    type: "number",
    placeholder: "12",
  },
  {
    name: "width",
    label: "width (mm)",
    type: "number",
    placeholder: "12",
  },
  {
    name: "length",
    label: "length (mm)",
    type: "number",
    placeholder: "12",
  },
  {
    name: "EnergyLabel ",
    label: "Energy Label ",
    type: "selct",

    placeholder: "F",
    options: [{ label: "F", value: "" }],
  },
  {
    name: "Type Approval",
    label: "Type Approval",
    type: "text",
  },
  {
    name: "Vehicle Identification Number (VIN)",
    label: "Vehicle Identification Number (VIN)",
    type: "text",
  },
  {
    name: "Reference",
    label: "Reference",
    type: "text",
  },
];
const detailedDataInput = [
  {
    name: "disability-friendly",
    label: "Disability-Friendly",
    type: "checkbox",
  },
  {
    name: "direct/parallel-import",
    label: "Direct/parallel import",
    type: "checkbox",
  },
  {
    name: "raceCar",
    label: "Race Car",
    type: "checkbox",
  },
  {
    name: "tuning",
    label: "Tuning",
    type: "checkbox",
  },
  {
    name: "accidentVehicle",
    label: "Accident Vehicle",
    type: "checkbox",
  },
];

const additionalDetail = [
  {
    name: "additionalTitle",
    label: "Additional Title",
    // required: true,
    type: "textarea",
  },
  {
    name: "vehicleDescription",
    label: "Vehicle Description",
    required: true,
    type: "textarea",
    options: [{ value: "-", label: "petrol" }],
  },
];

const vehicleDocumentInputs = [
  {
    name: "purchasePrice_CHF",
    label: "Vehicle Purchase Price",
    type: "number",
    // required: true,
    placeholder: "80’000 CHF",
  },
  {
    name: "seller",
    label: "Seller",
    type: "text",
    placeholder: "Enter Seller",
  },
  {
    name: "purchaseDate",
    label: "Purchase Date",
    type: "date",
    placeholder: "DD.MM.YYYY",
  },
  {
    name: "plannedInvestment",
    label: "Planned Investment",
    type: "number",
    placeholder: "10’000 CHF",
  },
  {
    name: "document",
    label: "Document",
    type: "file",
  },
];
const interfaceInputs = [
  {
    name: "email",
    label: "Email",
    type: "email",
    required: true,
    placeholder: "abc@gmail.com",
  },
  {
    name: "password",
    label: "password",
    type: "password",
    placeholder: "*********",
  },
  {
    name: "Private-key",
    label: "Private-key",
    type: "text",
    placeholder: "private key",
  },
];
const previousOwnerDataInput = [
  {
    name: "ownerType",
    label: "Owner Type",
    type: "select",
    options: [
      { value: "", label: "Select Owner" },
      { value: "firstOwner", label: "First Owner" },
      { value: "secondOwner", label: "Second Owner" },
      { value: "thirdOwner", label: "Third Owner" },
    ],
  },
  {
    name: "name",
    label: "Name of Previous Owner",
    type: "text",
    placeholder: "Add Name",
  },
  {
    name: "from",
    label: "From",
    type: "date",
    placeholder: "DD.MM.YYYY",
  },
  {
    name: "until",
    label: "Until",
    placeholder: "DD.MM.YYYY",
    type: "date",
  },
  {
    name: "yearOfBirth",
    label: "Year of Birth",
    type: "text",
    placeholder: "YYYY",
  },

  {
    name: "drivenKilometers",
    label: "Driven Kilometers",
    type: "number",
    placeholder: "88’000  km",
  },
  {
    name: "owner_purchasePrice_CHF",
    label: "Purchase Price",
    type: "number",
    placeholder: "10000",
  },
  {
    name: "status",
    label: "Status",
    type: "select",
    options: [
      { value: "", label: "Select Status" },
      { value: "A+", label: "A+" },
      { value: "A", label: "A" },
      { value: "B+", label: "B+" },
      { value: "B", label: "B" },
      { value: "C+", label: "C+" },
      { value: "C", label: "C" },
    ],
  },
];
const addVehicleHistoryDataInput = [
  {
    name: "type",
    label: "Type",
    type: "select",
    options: [
      { label: "Ownership Change", value: "ownership_change" },
      { label: "Accident Report", value: "accident_report" },
      { label: "Service/Maintenance", value: "service_maintenance" },
      { label: "Insurance Claim", value: "insurance_claim" },
      { label: "Registration Renewal", value: "registration_renewal" },
      { label: "Title Change", value: "title_change" },
      { label: "Loan/Lease Record", value: "loan_lease_record" },
      { label: "Odometer Reading", value: "odometer_reading" },
      { label: "Emission Test", value: "emission_test" },
      { label: "Theft Report", value: "theft_report" },
      { label: "Recall Notice", value: "recall_notice" },
      {
        label: "Modification/Customization",
        value: "modification_customization",
      },
    ],
  },
  {
    name: "historyLocation",
    label: "Location",
    type: "text",
    placeholder: "Enter Location",
  },
  {
    name: "date",
    label: "Date",
    type: "date",
    placeholder: "DD.MM.YYYY",
  },
];
const addVehicleInvestmentDataInput = [
  {
    name: "investmentFor",
    label: "Investment For",
    type: "text",
    placeholder: "Wheel repair etc ...",
  },
  {
    name: "amount_CHF",
    label: "Amount",
    type: "number",
    placeholder: "Enter amount ",
  },
  {
    name: "investmentLocation",
    label: "Investment Location",
    type: "text",
    placeholder: "Enter location where you spend",
  },
];
export {
  bodyTypes,
  editInitialValues,
  vehicleValidation,
  editVehicleValidation,
  addVehicleFirst,
  addVehicleThird,
  vehicleFeatures,
  vehicleConditionInputs,
  vehiclePriceInputs,
  optionalEquipmentInput,
  optionalEquipmentTwoInput,
  detailedDataInput,
  vehicleDocumentInputs,
  previousOwnerDataInput,
  addVehicleHistoryDataInput,
  makeAndModelSecondInputs,
  makeAndModelSecondConditionInputs,
  technicaldataInputs,
  interfaceInputs,
  additionalDetail,
  addVehicleInvestmentDataInput,
};
